ACTION_PREDICT = "ACTION_PREDICT"
ACTION_MONITOR = "ACTION_MONITOR"
ACTION_FALLBACK = "ACTION_FALLBACK"
ACTION_ABSTAIN = "ACTION_ABSTAIN"

REASON_DATA_CONTRACT = "DATA_CONTRACT"
REASON_CONFORMAL_UNCERTAIN = "CONFORMAL_UNCERTAIN"
REASON_HARD_DRIFT = "HARD_DRIFT"
REASON_SOFT_DRIFT = "SOFT_DRIFT"
REASON_PREDICTION_ERROR = "PREDICTION_ERROR"

FALLBACK_SCHEMA_MISMATCH = "SCHEMA_OR_FEATURE_MISMATCH"
